apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fastapi-operator-role
rules:
- apiGroups: ["yourcompany.com"]
  resources: ["fastapideployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
